[project]
name = "ml-detector"
version = "v0.5.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
  "fastapi==0.140.13",
  "opencv-python-headless==5.0.0.93",
  "python-multipart==0.0.32",
  "ultralytics==8.4.112",
  "uvicorn==0.51.0",
]

[project.optional-dependencies]
cpu = [
  "torch==2.13.0+cpu",
  "torchvision==0.28.0+cpu",
]
cuda = [
  "torch==2.11.0+cu128",
  "torchvision==0.26.0+cu128",
]
[tool.uv]
environments = [
  "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

conflicts = [
  [
    { extra = "cpu" },
    { extra = "cuda" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "torch-cpu", extra = "cpu" },
  { index = "torch-cuda", extra = "cuda" },
]
torchvision = [
  { index = "torch-cpu", extra = "cpu" },
  { index = "torch-cuda", extra = "cuda" },
]

[[tool.uv.index]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "torch-cuda"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
  "basedpyright==1.39.9",
  "ruff==0.15.22",
  "pytest",
  "pytest-asyncio",
  "httpx",
]

[tool.basedpyright]
# TODO: switch to "recommended"
typeCheckingMode = "strict"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["ALL"]
fixable = ["ALL"]
ignore = [
  "COM812",  # trailing comma missing - conflicts with formatter
  "FIX",  # flake8-fixme
  "TD",   # flake8-todo
  "D203", # 1 blank line required before class docstring
  "D212", # Multi-line docstring summary should start at the first line
]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
