---
name: publish docker image

on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - .github/**

jobs:
  docker-build-push:
    uses: techtales-io/github-workflows/.github/workflows/docker-push.yaml@ecc2ec9aad03311eae6f69ac571430fcdc773211 # v0.5.8
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      runner: ubuntu-latest
      tags: |
        type=semver,pattern={{version}}

  create-release:
    needs: docker-build-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # https://github.com/marketplace/actions/gh-release
      - name: create release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
