---
name: publish docker image

on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - .github/**

jobs:
  docker-build-push:
    uses: techtales-io/github-workflows/.github/workflows/docker-push.yaml@32543b44ee214e89e422e08707b010d6a6b29451 # v0.5.2
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      runner: ubuntu-latest
      tags: |
        type=semver,pattern={{version}}

  create-release:
    needs: docker-build-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # https://github.com/marketplace/actions/gh-release
      - name: create release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
