---
name: build docker image

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - .github/**

jobs:
  docker-build:
    uses: techtales-io/github-workflows/.github/workflows/docker-build.yaml@087a877c5029965026268769fbabe16cc00d76f4 # v0.5.5
    permissions:
      contents: read
      packages: read
    with:
      runner: ubuntu-latest
