---
name: build docker image

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - .github/**

jobs:
  docker-build:
    uses: techtales-io/github-workflows/.github/workflows/docker-build.yaml@ecc2ec9aad03311eae6f69ac571430fcdc773211 # v0.5.8
    permissions:
      contents: read
      packages: read
    with:
      runner: ubuntu-latest
