---
name: build docker image

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - .github/**

jobs:
  docker-build:
    uses: techtales-io/github-workflows/.github/workflows/docker-build.yaml@a456be77f7ef4b465b4fdd3dd426f47588cd9e49 # v0.5.1
    permissions:
      contents: read
      packages: read
    with:
      runner: ubuntu-latest
